api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "dynamic-discount"
type = "function"
uid = "1ae30357-b717-f070-bdef-66ffe02ca69029310b72"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
